// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4FPxP41DmtiZ3L0GSl0mV2G_sNgmMr4',
    appId: '1:403509578818:web:f09ead235b3364811231db',
    messagingSenderId: '403509578818',
    projectId: 'campusmartapp-b51e8',
    authDomain: 'campusmartapp-b51e8.firebaseapp.com',
    storageBucket: 'campusmartapp-b51e8.firebasestorage.app',
    measurementId: 'G-62349RKQMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBieOVE7_TsqwuUJycuXGHsj6q43QIB0qQ',
    appId: '1:403509578818:android:0f5c00f69b0680ee1231db',
    messagingSenderId: '403509578818',
    projectId: 'campusmartapp-b51e8',
    storageBucket: 'campusmartapp-b51e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl0aXVMBW5MPrjXrgj80OimGPAjjhgQdc',
    appId: '1:403509578818:ios:3aab9ca6c6b8c9bc1231db',
    messagingSenderId: '403509578818',
    projectId: 'campusmartapp-b51e8',
    storageBucket: 'campusmartapp-b51e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl0aXVMBW5MPrjXrgj80OimGPAjjhgQdc',
    appId: '1:403509578818:ios:3aab9ca6c6b8c9bc1231db',
    messagingSenderId: '403509578818',
    projectId: 'campusmartapp-b51e8',
    storageBucket: 'campusmartapp-b51e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB4FPxP41DmtiZ3L0GSl0mV2G_sNgmMr4',
    appId: '1:403509578818:web:a1da00ac15523cf71231db',
    messagingSenderId: '403509578818',
    projectId: 'campusmartapp-b51e8',
    authDomain: 'campusmartapp-b51e8.firebaseapp.com',
    storageBucket: 'campusmartapp-b51e8.firebasestorage.app',
    measurementId: 'G-DNZMXV6ZGW',
  );
}
